baseURL = 'https://changlecat.github.io/Changle-Scape'
# baseURL = 'https://example.org/' #! 本地运行请改成这个
languageCode = 'zh-CN'
title = 'My New Hugo Site'

[[menus.main]]
name = 'Home'
pageRef = '/'
weight = 10

[[menus.main]]
name = 'Posts'
pageRef = '/posts'
weight = 20

[[menus.main]]
name = 'Tags'
pageRef = '/tags'
weight = 30

[module]
  [module.hugoVersion]
    extended = false
    min = "0.147.0"
