name = 'Changle-Scape'
license = 'MIT'
licenselink = 'https://github.com/ChangleCat/Changle-Scape/blob/master/LICENSE'
description = 'Modified from Hugo-Landscape'

# The home page of the theme, where the source can be found
homepage = 'https://github.com/ChangleCat/Changle-Scape'

# If you have a running demo of the theme
demosite = 'https://changlecat.github.io/Changle-Scape/'

# Taxonomy terms
tags = ['blog']
features = ['unocss', 'swup']


# If the theme has a single author
[author]
  name = 'Changle_cat'
  homepage = 'https://changlecat.me/'

# If porting an existing theme
[original]
  author = '恐咖兵糖'
  homepage = 'https://www.ftls.xyz'
  repo = 'https://github.com/kkbt0/Hugo-Landscape'
