baseURL = 'https://changlecat.github.io/Changle-Scape'
# baseURL = 'https://example.org/'  #! 本地运行请改成这个
languageCode = 'zh-CN'
hasCJKLanguage = true
title = 'Changle-Scape'
theme = "../.."
enableRobotsTXT = true

[params.author]
  name = "Changle_cat"
  homepage ="https://changlecat.me/"
  description = "浮生若梦，为欢几何"
  email = "cthulhu@changlecat.me"
  twitterURL = "https://x.com/Changle_cat"
  gitHubURL = "https://github.com/ChangleCat"
  bilibiliURL = "https://space.bilibili.com/313519315"

[params]
  title = "Changle-Scape"
  avatarPath = "img/avatar.webp"
  description = "我们的征途是星辰大海！"
  bannerPath = "img/sky.webp"
  announcement = "这里是announcement"
  establishDate = 2025-01-24
  math = false  # 默认不启用MathJax渲染
  comments = false
  keywords = "Hugo, theme, Changle-Scape"

[params.twikoo]
  enable = false
  envId = ""

[taxonomies]
  author = "authors"
  category = "categories"
  tag = "tags"
  series = "series"

    
[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      hardWraps = true
    [markup.goldmark.extensions]
      [markup.goldmark.extensions.passthrough]
        enable = true
        [markup.goldmark.extensions.passthrough.delimiters]
          block = [['\[', '\]'], ['$$', '$$']]
          inline = [['\(', '\)']]
[Permalinks]
  # posts = ":year/:month/:filename"
  posts = "/posts/:slug"

[sitemap]
  changefreq = "weekly"
  filename = "sitemap.xml"
  priority = 0.5
