baseURL = 'https://changlecat.github.io/Changle-Scape'
# baseURL = 'https://example.org/'  #! 本地运行请改成这个
languageCode = 'zh-CN'
title = 'Changle-Scape'
theme = "../.."
enableRobotsTXT = true

[params.author]
  name = "Changle_cat"
  # homepage ="https://www.ftls.xyz"
  homepage =""
  description = "浮生若梦，为欢几何"

[params]
  title = "Changle-Scape"
  avatarPath = "img/avatar.webp"
  description = "我们的征途是星辰大海！"
  banner = "https://www.dmoe.cc/random.php"
  announcement = "这里是announcement"
  establishYear = 2025
  math = false  # 默认不启用MathJax渲染

[taxonomies]
  author = "authors"
  category = "categories"
  tag = "tags"
  series = "series"

[markup.goldmark.renderer]
    hardWraps = true
    
[Permalinks]
  # posts = ":year/:month/:filename"
  posts = "/posts/:slug"

[sitemap]
  changefreq = "weekly"
  filename = "sitemap.xml"
  priority = 0.5
